import React, { useState, useEffect } from 'react'
import Axios from "axios"
import { api } from "../apiPath.js"

function UsersTable() {


  const [SQLQuery, setSQLQeury] = useState("");
  const [queryResponse, setQueryResponse] = useState([]);

  const [userID, setUserID] = useState(0);
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");



  useEffect(() => {
      Axios.get(`${api.url}/api/Users`).then((response) => {
      setQueryResponse(response.data);
    });
  }, []);


  const insertUserQuery = () => {
    Axios.post(`${api.url}/api/Users/Insert`, {
      username: username,
      email: email,
    }).then((response) => {
      if (response.data) {
        Axios.get(`${api.url}/api/Users`).then((response) => {
          setQueryResponse(response.data);
        });
        alert("successful query");

      } else alert("Failed query");
    });
  };

  const updateQuery = (ID) => {};

  const deleteQuery = (ID) => {
    return () => {
      Axios.post(`${api.url}/api/Users/Delete`, {
        userID: ID,
      }).then((response) => {
        if (response) {
          Axios.get(`${api.url}/api/Users`).then((response) => {
            setQueryResponse(response.data);
          });
          alert("successful query");
        } else alert("Failed query");
      });
    };
  };



    return (
  <div className="home__container">
  <form>
    <div className="container table-responsive home__container my-5">
    <table className="table ">
        <thead>
        <tr>
            <th>userID</th>
            <th>username</th>
            <th>email</th>
            <th>new entry</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><input
                type="text"
                className="form-control"
                placeholder="autogenerated"
                disabled
                name="userID"
                onChange={(e) => {
                  setUserID(e.target.value);
                }}
              /></td>
            <td><input
                type="text"
                className="form-control"
                placeholder="username"
                name="username"
                onChange={(e) => {
                  setUsername(e.target.value);
                }}
              /></td>
            <td><input
                type="text"
                className="form-control"
                placeholder="email"
                name="email"
                onChange={(e) => {
                  setEmail(e.target.value);
                }}
              /></td>
            <td><button 
                  type="button" 
                  className="btn btn-primary" 
                  data-dismiss="modal"
                  onClick={insertUserQuery}
                  >
                    Add
                  </button></td>
        </tr>
        </tbody>
    </table>
    </div>
  </form>

        <div class="container table-responsive home__container my-5">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>userID</th>
                <th>username</th>
                <th>email</th>
              </tr>
            </thead>
            <tbody>

            {queryResponse.map((user) => {
                return (
                  <tr>
                    <td>{user.userID}</td>
                    <td>{user.username}</td>
                    <td>{user.email}</td>
                    <td>
                    <button 
                    type="button" 
                    className="btn btn-secondary" 
                    data-dismiss="modal"
                    >
                      Update
                    </button>
                    <button 
                      type="button" 
                      className="btn btn-danger" 
                      data-dismiss="modal"
                      onClick={deleteQuery(user.userID)}
                      >
                        Delete
                     </button>
                     </td>
                  </tr>

                );
              })}

            </tbody>
          </table>
        </div>
      </div>
    )
}

export default UsersTable
